### ISSUE TITLE
引导使用情况汇报，附：已成功升级10.15.4

### ISSUE THREAD

**Issue by ZHonry** [Leoyzen/M920x-Hackintosh-EFI#4]
从远景知道大大的oc引导，汇报一下引导的使用情况：
Lenovo M920x
CPU: i5-8500T 2.1GHz
Motherboard: Q370
BIOS: M1UKT50A
GPU: UHD 630
Mem: 金士顿 骇客神条 16G * 1
NVMe: 970EVO 1T
Wifi/Bluetooth: BCM94360CD
因使用苹果拆机网卡，对配置修改如下：
1、DeviceProperties下删除网卡PCI信息
2、删除所以网卡和蓝牙驱动
3、修改显卡ID为07009B3E 
4、机型设置mini8.1（折腾完成后换imac19.1看下效果如何）

下方设置为了关闭cfg，关闭cfg后恢复设置
勾选上 opencore 中以下的选项
Kernel-Quirks-AppleCpuPmCfgLock: yes
Kernel-Quirks-AppleXcpmCfgLock: yes

打开 show_picker 选项，然后在引导中 setup_var 进入 EFI 命令行
关闭 CFG_Lock：setup_var 0x721 0x00
修复 DVMT
将 Pre-Allocate Mem 修改为 64M（最大可选项）：setup_var 0xA44 0x2
将 Allocate Mem 修改为 Max：setup_var 0xA45 0x3
其他保持不变，目前测试正常，使用DP口，无HDMI线未测试是否正常。变频仅3.2和3.3两档，声卡目前没耳机和麦克风没测，内置喇叭为了给天线位置，直接拆了，目前使用显示器声音。

**Comment by Leoyzen** [comment]
为啥要开AppleCpuPmCfgLock和AppleXcpmCfgLock，如果已经 bios 关闭力 cfg 锁，这两个可以设置为 no。否则的话电源管理、变频是不正常的。

**Comment by ZHonry** [comment]
> 为啥要开AppleCpuPmCfgLock和AppleXcpmCfgLock，如果已经bios关闭力cfg锁，这两个可以设置为no。否则的话电源管理，转换是不正常的。

不开这两个我引导都进不去，临时关掉然后在setup_var中关闭cfg和修改dvmt的，修改后就关掉了，后面一切正常，变频今晚我再看看什么原因

**Comment by wdrich** [comment]
楼主请问是用的94360CS2 需要改造散热器吗

**Comment by ZHonry** [comment]
> 楼主请问是用的94360CS2 需要改造散热器吗

我直接加的 没改散热 理论上来讲 这个热量影响不大

**Comment by wdrich** [comment]
您是

> > 楼主请问是用的94360CS2 需要改造散热器吗
> 
> 我直接加的 没改散热 理论上来讲 这个热量影响不大

您是94360CS2用的反接方式吗

**Comment by wdrich** [comment]
> > 楼主请问是用的94360CS2 需要改造散热器吗
> 
> 我直接加的 没改散热 理论上来讲 这个热量影响不大

你好 BCM94360CD这是什么网卡

**Comment by ZHonry** [comment]
> > > 楼主请问是用的94360CS2 需要改造散热器吗
> > 
> > 
> > 我直接加的 没改散热 理论上来讲 这个热量影响不大
> 
> 你好 BCM94360CD这是什么网卡

老版的苹果拆机卡，现在好像是943602CDP最好

**Comment by wdrich** [comment]
> > > > 楼主请问是用的94360CS2 需要改造散热器吗
> > > 
> > > 
> > > 我直接加的 没改散热 理论上来讲 这个热量影响不大
> > 
> > 
> > 你好 BCM94360CD这是什么网卡
> 
> 老版的苹果拆机卡，现在好像是943602CDP最好

谢谢 可以分享下您的EFI吗

**Comment by wdrich** [comment]
> > > > 楼主请问是用的94360CS2 需要改造散热器吗
> > > 
> > > 
> > > 我直接加的 没改散热 理论上来讲 这个热量影响不大
> > 
> > 
> > 你好 BCM94360CD这是什么网卡
> 
> 老版的苹果拆机卡，现在好像是943602CDP最好

wdrich@163.com

**Comment by ZHonry** [comment]
> > > > > 楼主请问是用的94360CS2 需要改造散热器吗
> 
> > > > 
> 
> > > > 
> 
> > > > 我直接加的 没改散热 理论上来讲 这个热量影响不大
> 
> > > 
> 
> > > 
> 
> > > 你好 BCM94360CD这是什么网卡
> 
> > 
> 
> > 老版的苹果拆机卡，现在好像是943602CDP最好
> 
> 
> 
> 谢谢 可以分享下您的EFI吗

用的就是这个efi
